---
- name: Configure timezone
  hosts: builder
  become: true
  tags: timezone
  tasks:
    - import_role:
        name: stackhpc.timezone
      vars:
        timezone: "{{ cluster_timezone }}"

- name: sshd config for user access
  hosts: sshd
  tags: user-access
  become: true
  tasks:
    - name: Install SSH public CA key
      ansible.builtin.get_url:
        url: https://ca.isambard.ac.uk/public_key
        dest: /etc/ssh/conch_ssh_ca.key
        force: true
        mode: "u=rw,g=,o="
        owner: root
        group: root

- name: motd
  hosts: login
  tags: motd
  become: true
  tasks:
    - name: Install MOTD
      ansible.builtin.copy:
        src: "{{ appliances_environment_root }}/../site/files/motd"
        dest: "/etc/motd"
        force: true
        mode: "u=rw,g=r,o=r"
        owner: root
        group: root
