---

- name: Configure Slurm MPI
  hosts: control
  become: true
  tags: openhpc
  tasks:
    - name: Template mpi.conf
      ansible.builtin.template:
        src: "{{ lookup('env', 'APPLIANCES_ENVIRONMENT_ROOT') }}/../site/templates/mpi.conf.j2"
        dest: /etc/slurm/mpi.conf
        owner: root
        group: root
        mode: 0644

- name: Set up SSSD
  hosts: sssd
  tags: sssd
  become: true
  tasks:
    - name: Copy FreeIPA server cert
      ansible.builtin.copy:
        src: "{{ appliances_environment_root }}/../site/files/dl-auth.acrc.bris.ac.uk.cert"
        dest: "/etc/sssd/dl-auth.acrc.bris.ac.uk.cert"

    - name: "Set SSSD for sudo: remove line"
      ansible.builtin.lineinfile:
        state: absent
        path: /etc/nsswitch.conf
        regexp: '^sudoers:'
    
    - name: "Set SSSD for sudo: insert line"
      ansible.builtin.lineinfile:
        state: present
        path: /etc/nsswitch.conf
        insertafter: EOF
        line: "sudoers: files sss"
