---

- name: Configure Slurm MPI
  hosts: control
  become: true
  tags: openhpc
  tasks:
    - name: Template mpi.conf
      ansible.builtin.template:
        src: "{{ lookup('env', 'APPLIANCES_ENVIRONMENT_ROOT') }}/../site/templates/mpi.conf.j2"
        dest: /etc/slurm/mpi.conf
        owner: root
        group: root
        mode: 0644

- name: Set up SSSD
  hosts: sssd
  tags: sssd
  become: true
  tasks:
    - name: Copy FreeIPA server cert
      ansible.builtin.copy:
        src: "{{ appliances_environment_root }}/../site/files/dl-auth.acrc.bris.ac.uk.cert"
        dest: "/etc/sssd/dl-auth.acrc.bris.ac.uk.cert"

    - name: "Set SSSD for sudo: remove line"
      ansible.builtin.lineinfile:
        state: absent
        path: /etc/nsswitch.conf
        regexp: '^sudoers:'
    
    - name: "Set SSSD for sudo: insert line"
      ansible.builtin.lineinfile:
        state: present
        path: /etc/nsswitch.conf
        insertafter: EOF
        line: "sudoers: files sss"

# TODO: Remove when upstream patch to sshd role is merged from 2.15
- name: "Hotfix: Set MaxStartups to avoid throttling"
  hosts: control
  tags: sshd
  become: true
  tasks:
    - name: Set MaxStartups
      ansible.builtin.lineinfile:
        state: present
        path: /etc/ssh/sshd_config.d/11-ansible-maxstartups.conf
        create: true
        insertafter: EOF
        line: "MaxStartups 100:30:200"

    - name: Restart sshd service
      ansible.builtin.systemd_service:
        name: sshd
        state: restarted

- name: Remove old tmpfs configuration
  hosts: compute
  tags: tmpfs
  become: true
  tasks:
    - name: Disable tmp.mount service
      ansible.builtin.systemd:
        name: tmp.mount
        enabled: false

    - name: Ensure /tmp is not mounted under tmpfs
      ansible.posix.mount:
        path: "/tmp"
        state: "absent"

- name: Configure namespace/tmpfs plugin
  hosts: control
  tags: tmpfs
  become: true
  tasks:
    - name: Ensure job_container.conf exists
      ansible.builtin.template:
        src: "job_container.conf.j2"
        dest: "/etc/slurm/job_container.conf"
        owner: root
        group: root
        mode: "0644"
